// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqJWqAv_sHkIimabVu0FHcVfG5HmrlSFs',
    appId: '1:566986428664:web:10f83387b67348cd3fab0d',
    messagingSenderId: '566986428664',
    projectId: 'notes-6acaa',
    authDomain: 'notes-6acaa.firebaseapp.com',
    storageBucket: 'notes-6acaa.firebasestorage.app',
    measurementId: 'G-PG7VE1MFZ2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOmBqd3tZyllpI4za_MDrcfhp8xb2DT8g',
    appId: '1:566986428664:android:4d74c2bb91cbf0d73fab0d',
    messagingSenderId: '566986428664',
    projectId: 'notes-6acaa',
    storageBucket: 'notes-6acaa.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwXPbubWo6FVTj6J1hHLb9-MkjJ_X9Wp8',
    appId: '1:566986428664:ios:9d364289f1ec72b93fab0d',
    messagingSenderId: '566986428664',
    projectId: 'notes-6acaa',
    storageBucket: 'notes-6acaa.firebasestorage.app',
    iosClientId: '566986428664-mkpn8p25c44qceh5gvudphdfg1c4ajsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.task7FlutterfireNotes',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwXPbubWo6FVTj6J1hHLb9-MkjJ_X9Wp8',
    appId: '1:566986428664:ios:9d364289f1ec72b93fab0d',
    messagingSenderId: '566986428664',
    projectId: 'notes-6acaa',
    storageBucket: 'notes-6acaa.firebasestorage.app',
    iosClientId: '566986428664-mkpn8p25c44qceh5gvudphdfg1c4ajsp.apps.googleusercontent.com',
    iosBundleId: 'com.example.task7FlutterfireNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqJWqAv_sHkIimabVu0FHcVfG5HmrlSFs',
    appId: '1:566986428664:web:f2bd70f5dc1b13443fab0d',
    messagingSenderId: '566986428664',
    projectId: 'notes-6acaa',
    authDomain: 'notes-6acaa.firebaseapp.com',
    storageBucket: 'notes-6acaa.firebasestorage.app',
    measurementId: 'G-B0LP1D6WK6',
  );
}
